# Working directory (will read all directories and files relative to this path)
root = "."
# Directory that contains test data (e.g. snapshots, fixtures, etc.)
testdata_dir = "testdata"
# Directory to store temporary files (like the binary file)
tmp_dir = "tmp"

[build]
  args_bin = []
# Binary file yields from `cmd`.
  bin = "./tmp/main"
# Run a shell command
  cmd = "go build -o ./tmp/main ."
# It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
# Exclude specific files
  exclude_file = []
# Exclude specific regular expressions
  exclude_regex = ["_test.go"]
# Exclude unchanged files
  exclude_unchanged = false
# Follow symlink for directories
  follow_symlink = false
# Customize binary (e.g you can setup environment variables)
  full_bin = ""
# Watch these directories
  include_dir = []
# Watch these filename extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
# Watch these files
  include_file = []
 # Delay after sending Interrupt signal
  kill_delay = "0s"
# Name of the log file placed in your tmp_dir.
  log = "build-errors.log"
# Poll files for changes instead of using fsnotify.
  poll = false
# Poll interval for file changes
  poll_interval = 0
# Array of commands to run after each build
  post_cmd = ["echo 'Shutting down...'"]
# Array of commands to run before each build
  pre_cmd = ["echo 'Starting...'"]
# Rerun binary
  rerun = false
# Delay after each execution of the command
  rerun_delay = 500
# Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
# Stop running old binary when build errors occur.
  stop_on_error = false

[color]
#  Customize each part's color. If not set, it will use the default color
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
# Only show main log (silences watcher, build, runner)
  main_only = false
# Show log time
  time = false

[misc]
# Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true

# Enable live-reloading on the browser.
# [proxy]
#  enabled = true
#  proxy_port = 8090
#  app_port = 8080
